version: 2
models:
  - name: table1
    description: table1
    columns:
      - name: id
        description: ""
        meta:
          dimension:
            type: number
      - name: values
        description: ""
        meta:
          dimension:
            type: number
  - name: table2crud
    description: table2
    columns:
      - name: id
        description: ""
        meta:
          dimension:
            type: number
      - name: value
        description: ""
      - name: values
        description: ""
        meta:
          dimension:
            type: number
  - name: table3
    description: table3
    columns:
      - name: id
        description: ""
        meta:
          dimension:
            type: number
      - name: nilai_table_1
        description: ""
        meta:
          dimension:
            type: number
      - name: nilai_table_2
        description: ""
        meta:
          dimension:
            type: number
      - name: kali
        description: ""
        meta:
          dimension:
            type: number
